### ISSUE TITLE
SSL cert verification errors on vagrant provision with chef solo (puling cookbooks from a chef 11 server)

### ISSUE THREAD

**Issue by svanzoest** [berkshelf/vagrant-berkshelf#113]
While I ran into #108, I am also unable to update from within vagrant, but with berkshelf directly against our chef 11 server works fine. I assume it is possible that the vagrant-berkshelf plugin is unable to find the CA certs bundle?

For now I just `export BERKSHELF_PATH=~/.berkshelf` and use `berks install` to pull down the packages and things work as expected.

On Ubuntu Precise 12.04.3 LTS 64-bit with Vagrant 1.3.5 and vagrant-berkshelf (1.3.4)

```
$ vagrant provision
[default] Setting up as a  based host...
[default] The cookbook path '/home/svanzoest/.berkshelf/default/vagrant/berkshelf-20130829-17827-84psw1-default' doesn't exist. Ignoring...
[Berkshelf] This version of the Berkshelf plugin has not been fully tested on this version of Vagrant.
[Berkshelf] You should check for a newer version of vagrant-berkshelf.
[Berkshelf] If you encounter any errors with this version, please report them at https://github.com/RiotGames/vagrant-berkshelf/issues
[Berkshelf] You can also join the discussion in #berkshelf on Freenode.
[Berkshelf] Updating Vagrant's berkshelf: '/home/svanzoest/.berkshelf/default/vagrant/berkshelf-20130829-17827-84psw1-default'
[Berkshelf] Using mycookbook (0.8.0) at '../mycookbook'
/home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/responses.rb:29:in `value': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Ridley::Errors::ConnectionFailed)
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/proxies/actor_proxy.rb:25:in `_send_'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/pool_manager.rb:41:in `_send_'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/pool_manager.rb:122:in `method_missing'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/proxies/actor_proxy.rb:21:in `send'
    from /home/svanzoest/.vagrant.d/gems/gems/ridley-1.5.3/lib/ridley/resource.rb:132:in `raw_request'
    from /home/svanzoest/.vagrant.d/gems/gems/ridley-1.5.3/lib/ridley/resource.rb:123:in `request'
    from /home/svanzoest/.vagrant.d/gems/gems/ridley-1.5.3/lib/ridley/resources/cookbook_resource.rb:223:in `versions'
    from /home/svanzoest/.vagrant.d/gems/gems/ridley-1.5.3/lib/ridley/resources/cookbook_resource.rb:127:in `satisfy'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:67:in `dispatch'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/internal_pool.rb:59:in `call'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/internal_pool.rb:59:in `block in create'
    from /home/svanzoest/.vagrant.d/gems/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `call'
    from /home/svanzoest/.vagrant.d/gems/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
    from (celluloid):0:in `remote procedure call'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/calls.rb:95:in `value'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/proxies/sync_proxy.rb:28:in `method_missing'
    from /home/svanzoest/.vagrant.d/gems/gems/celluloid-0.14.1/lib/celluloid/legacy.rb:14:in `method_missing'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/locations/chef_api_location.rb:171:in `target_cookbook'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/locations/chef_api_location.rb:151:in `download'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/downloader.rb:119:in `download_location'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/downloader.rb:88:in `block in download'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/downloader.rb:84:in `each'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/downloader.rb:84:in `download'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/resolver.rb:137:in `install_source'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/resolver.rb:57:in `add_source'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/resolver.rb:30:in `block in initialize'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/resolver.rb:29:in `each'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/resolver.rb:29:in `initialize'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/berksfile.rb:665:in `new'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/berksfile.rb:665:in `resolve'
    from /home/svanzoest/.vagrant.d/gems/gems/berkshelf-2.0.10/lib/berkshelf/berksfile.rb:418:in `install'
    from /home/svanzoest/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/install.rb:46:in `install'
    from /home/svanzoest/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/install.rb:30:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/provision.rb:54:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/svanzoest/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/configure_chef.rb:23:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/svanzoest/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/load_shelf.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/svanzoest/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/set_ui.rb:12:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/env_set.rb:19:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/machine.rb:147:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/provision/command.rb:26:in `block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/plugin/v2/command.rb:185:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/plugin/v2/command.rb:183:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/provision/command.rb:25:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/cli.rb:38:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/environment.rb:478:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.3.5/bin/vagrant:96:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

**Comment by daxgames** [comment]
@sethvargo - I know this is an old thread but it looks like your proposed solution 'may' be related to a remote_file download SSL verify issue I am having when I vagrant up a machine and try to provision with chef-solo.

Can you provide guidance as to how/where to place updated certs in the vagrant up'd vm so Chef can successfully use remote_file?

I have tried several places:

/etc/chef/trusted_certs
/opscode/chef/embedded/ssl/certs
/chef/trusted_certs

Now for the wrinkle, this is a Windows box.  I have also added certs to Windows and IE/Chrome is able to download files.
