### ISSUE TITLE
Could not determine Berks version. v3.0.0

### ISSUE THREAD

**Issue by dkinzer** [berkshelf/vagrant-berkshelf#212]
```
RuntimeError: Couldn't determine Berks version: #<Buff::ShellOut::Response:0x0000000338ef98 @exitstatus=1, @s
tdout="", @stderr="/home/dkinzer/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs
': Could not find 'berkshelf' (>= 0) among 90 total gem(s) (Gem::LoadError)\n\tfrom /home/dkinzer/.rbenv/vers
ions/2.1.2/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'\n\tfrom /home/dkinzer/.rbenv/versions/2.1.2
/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'\n\tfrom /home/dkinzer/.rbenv/versions/2.1.2/bin/b
erks:22:in `<main>'\n">                                                                                      
```

I'm getting this error after upgrading the vagrant-berkshelf plugin:

Version details:

```
(website)(website-1404)$vagrant version && vagrant plugin list 
Installed Version: 1.6.3                                       
Latest Version: 1.6.3                                          

You're running an up-to-date version of Vagrant!               
librarian-chef (0.0.4)                                         
vagrant-berkshelf (3.0.0)                                      
vagrant-login (1.0.1, system)                                  
vagrant-omnibus (1.4.1)                                        
vagrant-rackspace (0.1.9)                                      
vagrant-share (1.1.0, system)                                  
```

Gemfile

```
source "https://rubygems.org"       

gem "knife-solo"                    
gem "knife-solo_data_bag"           
gem "foodcritic"                    
gem "fog"                           
gem "berkshelf"                     
```

Vagrantfile

```
# berkshelf
 config.berkshelf.only = [                        
   "./attributes",                                
   "./recipes",                                   
   "./roles",                                     
   "./data_bags",                                 
   "./templates",                                 
   "./files",                                     
   "./metadata.rb",                               
   "./Thorfile",                                  
   "./Gemfile",                                   
   "./Berksfile",                                 
   "./test",                                      
 ]                                                
 config.berkshelf.enabled = true               

```

**Comment by ursachec** [comment]
Same as @pedrocarrico , @joestump 's solution worked for me on a MacBookPro11,1 with OS X Yosemite 10.10.2 installed.

```bash
export PATH="/opt/chefdk/bin:$PATH"
```

**Comment by mrjcleaver** [comment]
You might find https://github.com/docwhat/rbenv-chefdk useful

**Comment by monajalal** [comment]
I got the same error:

`Monas-MacBook-Pro:~ mona$ chef --v
Chef Development Kit Version: 0.15.16
chef-client version: 12.11.18
delivery version: master (444effdf9c81908795e88157f01cd667a6c43b5f)
berks version: ERROR
kitchen version: 1.10.0
Monas-MacBook-Pro:~ mona$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1713`

**Comment by docwhat** [comment]
I don't use RVM anymore but I was never able to get it to play nicely with ChefDK when I last played with it.  That's why I wrote the [rbenv-chefdk plugin](https://github.com/docwhat/rbenv-chefdk) mentioned above.
