### ISSUE TITLE
config.rb expand_path: no implicit conversion of Proc into String

### ISSUE THREAD

**Issue by rhardouin** [berkshelf/vagrant-berkshelf#228]
Hi,

I've just run OpenStack Monasca which uses vagrant-berkshelf-2.0.1 and got the following error:

```
/home/romain/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/config.rb:58:in 'expand_path': no implicit conversion of Proc into String (TypeError)
from /home/romain/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/config.rb:58:in 'validate'
from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/root.rb:68:in 'block in validate'
from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/root.rb:64:in 'each'
from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/root.rb:64:in 'validate'
from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:15:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /home/romain/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/configure_chef.rb:22:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /home/romain/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/load_shelf.rb:27:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /home/romain/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/set_ui.rb:11:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/env_set.rb:19:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in 'block in finalize_action'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/handle_box.rb:56:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in 'block in finalize_action'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in 'block in run'
from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in 'busy'
from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in 'run'
from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:53:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in 'block in run'
from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in 'busy'
from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in 'run'
from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:196:in 'action_raw'
from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:173:in 'block in action'
from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:440:in 'lock'
from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in 'call'
from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in 'action'
from /usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:82:in 'block (2 levels) in run'
```

config.rb:58 is:

``` ruby
 @client_key = File.expand_path(@client_key, machine.env.root_path.to_s)
```

So I made a dirty hack like this and it works fine:

``` ruby
if @client_key .kind_of? Proc
    @client_key = @client_key.call()
end
@client_key = File.expand_path(@client_key, machine.env.root_path.to_s)
```

I don't know at all vagrant-berkshelf, a neater fix is surely needed.

Best,
Romain

**Comment by cbreden** [comment]
@ehaselwanter Were you able to arrive at a working vagrant-berkshelf and vagrant-chef-zero combination?  I'm a bit baffled due to thinking this was a common setup.  From the vagrant-chef-zero readme:
> [Cookbooks] are uploaded via the Ridley gem. It is the same backend that Berkshelf uses, though I am sure my usage is not as complete. It expects a path to a cookbooks/ directory, or an array of paths to individual cookbooks. If you omit this field, you can have Berkshelf upload cookbooks as usual (It will find the Chef-Zero URL automatically).

I don't see where it sends the berks command (and ridley) the IP address it says it's uploading to.

**Comment by cristianmtr** [comment]
Caught the same bug. @rhardouin fix worked. Why hasn't this been fixed?
