### ISSUE TITLE
Test Kitchen crashes after installing vagrant berkshelf plugin

### ISSUE THREAD

**Issue by trahma** [berkshelf/vagrant-berkshelf#254]
After installing vagrant berkshelf running "kitchen test" crashes.  It appears that even though my GEM_PATH is configured correctly in my shell environment, it seems like that variable is lost.  I have the latest versions of Vagrant and ChefDK installed as well so I don't believe this to be a versioning issue.

```text
 ~/zathras kitchen test                                                                                                                                                       Wed Jan 14 01:43:31 CST 2015
-----> Starting Kitchen (v1.2.1)
-----> Cleaning up any prior instances of <default-ubuntu-1404>
-----> Destroying <default-ubuntu-1404>...
       Finished destroying <default-ubuntu-1404> (0m0.00s).
-----> Testing <default-ubuntu-1404>
-----> Creating <default-ubuntu-1404>...
       Bringing machine 'default' up with 'virtualbox' provider...
       The following berks command failed to execute:

           /Users/justin/.chefdk/gem/ruby/2.1.0/bin/berks --version --format json

       The stdout and stderr are shown below:

           stdout:
           stderr: /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'berkshelf' (>= 0) among 56 total gem(s) (Gem::LoadError)
       Checked in 'GEM_PATH=/Users/justin/.vagrant.d/gems:/opt/vagrant/bin/../embedded/gems', execute `gem env` for more information
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:322:in `to_spec'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'
        from /Users/justin/.chefdk/gem/ruby/2.1.0/bin/berks:22:in `<main>'
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
STDERR: The following berks command failed to execute:

    /Users/justin/.chefdk/gem/ruby/2.1.0/bin/berks --version --format json

The stdout and stderr are shown below:

    stdout:
    stderr: /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'berkshelf' (>= 0) among 56 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/justin/.vagrant.d/gems:/opt/vagrant/bin/../embedded/gems', execute `gem env` for more information
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:322:in `to_spec'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'
    from /Users/justin/.chefdk/gem/ruby/2.1.0/bin/berks:22:in `<main>'
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
```

**Comment by sethvargo** [comment]
@trahma you do not need the vagrant-berkshelf plugin to use berkshelf with Test Kitchen. It will automatically resolve dependencies itself without the plugin.

Furthermore, this issue has been fixed in https://github.com/test-kitchen/kitchen-vagrant/commit/24811d164e2757c51f3181062a5859e7335ed5c9 and is just waiting for a release :smile:
