### ISSUE TITLE
ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by modius** [berkshelf/vagrant-berkshelf#3]
Tried to update Berkshelf but failed.  Checked I have the latest XCode command line tools and _Vagrant version 1.1.0_.

```
Olorin:myface modius$ vagrant plugin install berkshelf-vagrant
[WARNING] Berkshelf not found in your Vagrant's RubyGems but your Vagrantfile is attempting
[WARNING] to require the Berkshelf Vagrant plugin! Install the Berkshelf Vagrant plugin or
[WARNING] remove the 'require "berkshelf/vagrant"' line from the top of your Vagrantfile.

If you installed Vagrant by RubyGems:
  Install Berkshelf by running: "gem install berkshelf"
If you installed Vagrant by one of the pre-packaged installers:
  Install Berkshelf by running: "vagrant gem install berkshelf"

Installing the 'berkshelf-vagrant' plugin. This can take a few minutes...
/Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:562:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

        /Applications/Vagrant/embedded/bin/ruby extconf.rb
creating Makefile

make
make: *** No rule to make target `/Applications/Vagrant/embedded/include/ruby-1.9.1/x86_64-darwin12.2.1/ruby/config.h', needed by `yajl.o'.  Stop.


Gem files will remain installed in /Users/modius/.vagrant.d/gems/gems/yajl-ruby-1.1.0 for inspection.
Results logged to /Users/modius/.vagrant.d/gems/gems/yajl-ruby-1.1.0/ext/yajl/gem_make.out
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:540:in `block in build_extensions'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:515:in `each'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:515:in `build_extensions'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:180:in `install'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:297:in `block in install'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each_with_index'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `install'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/action/install_gem.rb:27:in `block in call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/gem_helper.rb:42:in `block in with_environment'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/user_interaction.rb:40:in `use_ui'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/gem_helper.rb:41:in `with_environment'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/action/install_gem.rb:23:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/action/bundler_check.rb:20:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/action/builder.rb:109:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/command/base.rb:17:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/command/install.rb:28:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/plugins/commands/plugin/command/root.rb:47:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/cli.rb:46:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/lib/vagrant/environment.rb:406:in `cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.0/bin/vagrant:60:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

**Comment by vhosakot** [comment]
I saw the error `Failed to build gem native extension` too on CentOS 7.3 and vagrant 1.8.7.

I resolved it after installing ruby-devel and gcc (`yum -y install ruby-devel gcc`)
